language: php
os: linux
php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2

services:
  - postgresql

env:
  global:
    - APP_NAME=metadata
  jobs:
    - CLOUD=nextcloud CORE_BRANCH=stable24
    - CLOUD=nextcloud CORE_BRANCH=stable25
    - CLOUD=nextcloud CORE_BRANCH=stable26
    - CLOUD=nextcloud CORE_BRANCH=master

jobs:
  exclude:
    - php: 8.2
      env: CLOUD=nextcloud CORE_BRANCH=stable24
    - php: 8.2
      env: CLOUD=nextcloud CORE_BRANCH=stable25
  allow_failures:
    - env: CLOUD=nextcloud CORE_BRANCH=master

before_install:
  - if [ $CLOUD = 'nextcloud' ]; then wget -O before_install.sh https://raw.githubusercontent.com/gino0631/nextcloud-metadata/master/tests/travis_nextcloud_install.sh; fi
  - . ./before_install.sh $APP_NAME $CORE_BRANCH pgsql

script:
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml
