language: php
os: linux
dist: bionic
php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2

addons:
  apt:
    packages:
      - libonig4

services:
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - APP_NAME=metadata
  jobs:
    - CLOUD=nextcloud CORE_BRANCH=stable24
    - CLOUD=nextcloud CORE_BRANCH=stable25
    - CLOUD=nextcloud CORE_BRANCH=stable26
    - CLOUD=nextcloud CORE_BRANCH=stable27
    - CLOUD=nextcloud CORE_BRANCH=master

jobs:
  exclude:
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable26
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=stable27
    - php: 7.4
      env: CLOUD=nextcloud CORE_BRANCH=master
    - php: 8.2
      env: CLOUD=nextcloud CORE_BRANCH=stable24
    - php: 8.2
      env: CLOUD=nextcloud CORE_BRANCH=stable25
  allow_failures:
    - env: CLOUD=nextcloud CORE_BRANCH=master

before_install:
  - if [ $CLOUD = 'nextcloud' ]; then wget -O before_install.sh https://raw.githubusercontent.com/gino0631/nextcloud-metadata/master/tests/travis_nextcloud_install.sh; fi
  - . ./before_install.sh $APP_NAME $CORE_BRANCH pgsql

install:
  - composer install --prefer-dist --no-interaction

script:
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests
  - phpunit --version
  - phpunit --configuration phpunit.xml
